name: dutuku_e_commerce
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dartz: ^0.10.1
  system_design_flutter:
    path: packages/system_design_flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_bloc: ^9.1.1
  injectable: ^2.5.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  adaptive_theme: ^3.7.0
  ionicons: ^0.2.2
  carousel_slider: ^5.1.1
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/images/banner/
    - assets/images/product/

lint_staged:
  "lib/**.dart": dart format && dart fix --apply
