// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:dutuku_e_commerce/src/core/core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: AppEnv.FISEBASE_ANDROID_API_KEY,
    appId: AppEnv.FISEBASE_ANDROID_APP_ID,
    messagingSenderId: AppEnv.FIREBASE_MESSAGING_SENDER_ID,
    projectId: AppEnv.FIREBASE_PROJECT_ID,
    storageBucket: AppEnv.FIREBASE_STORAGE_BUCKET,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: AppEnv.FISEBASE_IOS_API_KEY,
    appId: AppEnv.FISEBASE_IOS_APP_ID,
    messagingSenderId: AppEnv.FIREBASE_MESSAGING_SENDER_ID,
    projectId: AppEnv.FIREBASE_PROJECT_ID,
    storageBucket: AppEnv.FIREBASE_STORAGE_BUCKET,
  );
}
